security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SONATA_ADMIN]
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        administrators:
            entity: { class: MalkosUserBundle:User }
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern:  ^/admin/login$
            security: false

        service_login:
            pattern:  ^/servicelogin$
            security: false

        admin_area:
             pattern: ^/admin
             provider: fos_userbundle
             http_basic: ~
             form_login:
                 login_path: /admin/login
                 check_path: /admin/login_check
                 use_referer: true
             stateless:  false
             logout:
                 path:   /logout
                 target: /

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    linkedin:           "/login/check-linkedin"
                    twitter:            "/login/check-twitter"
                    github:             "/login/check-github"
                login_path:        /login
                failure_path:      /login
 
                oauth_user_provider:
                    service: symfonysocial.user.provider
                failure_handler:     symfonysocial.oauthfailurehandler
            logout:       true
            anonymous:    true
 
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
 
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/servicelogin$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/*, role: ROLE_ADMIN }