services:
    sonata.admin.user:
        class: Malkos\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Users" }
        arguments:
            - ~
            - Malkos\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [MalkosUserBundle]]
            - [ setUserManager, [@fos_user.user_manager]]
